export interface StockMeta {
  symbol: string;
  name: string;
  sector: string;
}

export const STOCK_UNIVERSE: StockMeta[] = [
  { symbol: "AAPL",  name: "Apple",              sector: "Tech" },
  { symbol: "MSFT",  name: "Microsoft",          sector: "Tech" },
  { symbol: "GOOGL", name: "Alphabet A",         sector: "Tech" },
  { symbol: "AMZN",  name: "Amazon",             sector: "Consumer" },
  { symbol: "META",  name: "Meta Platforms",     sector: "Tech" },
  { symbol: "NVDA",  name: "NVIDIA",             sector: "Semis" },
  { symbol: "TSLA",  name: "Tesla",              sector: "Auto" },
  { symbol: "AMD",   name: "Advanced Micro",     sector: "Semis" },
  { symbol: "INTC",  name: "Intel",              sector: "Semis" },
  { symbol: "AVGO",  name: "Broadcom",           sector: "Semis" },
  { symbol: "ORCL",  name: "Oracle",             sector: "Tech" },
  { symbol: "CRM",   name: "Salesforce",         sector: "Tech" },
  { symbol: "ADBE",  name: "Adobe",              sector: "Tech" },
  { symbol: "NFLX",  name: "Netflix",            sector: "Media" },
  { symbol: "DIS",   name: "Disney",             sector: "Media" },
  { symbol: "UBER",  name: "Uber",               sector: "Consumer" },
  { symbol: "ABNB",  name: "Airbnb",             sector: "Consumer" },
  { symbol: "SHOP",  name: "Shopify",            sector: "Tech" },
  { symbol: "PYPL",  name: "PayPal",             sector: "Fintech" },
  { symbol: "SQ",    name: "Block",              sector: "Fintech" },
  { symbol: "COIN",  name: "Coinbase",           sector: "Fintech" },
  { symbol: "JPM",   name: "JPMorgan Chase",     sector: "Banks" },
  { symbol: "BAC",   name: "Bank of America",    sector: "Banks" },
  { symbol: "GS",    name: "Goldman Sachs",      sector: "Banks" },
  { symbol: "MS",    name: "Morgan Stanley",     sector: "Banks" },
  { symbol: "V",     name: "Visa",               sector: "Fintech" },
  { symbol: "MA",    name: "Mastercard",         sector: "Fintech" },
  { symbol: "WMT",   name: "Walmart",            sector: "Retail" },
  { symbol: "COST",  name: "Costco",             sector: "Retail" },
  { symbol: "NKE",   name: "Nike",               sector: "Consumer" },
  { symbol: "MCD",   name: "McDonald's",         sector: "Consumer" },
  { symbol: "SBUX",  name: "Starbucks",          sector: "Consumer" },
  { symbol: "KO",    name: "Coca-Cola",          sector: "Consumer" },
  { symbol: "PEP",   name: "PepsiCo",            sector: "Consumer" },
  { symbol: "PG",    name: "Procter & Gamble",   sector: "Consumer" },
  { symbol: "JNJ",   name: "Johnson & Johnson",  sector: "Health" },
  { symbol: "PFE",   name: "Pfizer",             sector: "Health" },
  { symbol: "LLY",   name: "Eli Lilly",          sector: "Health" },
  { symbol: "UNH",   name: "UnitedHealth",       sector: "Health" },
  { symbol: "XOM",   name: "Exxon Mobil",        sector: "Energy" },
  { symbol: "CVX",   name: "Chevron",            sector: "Energy" },
  { symbol: "BA",    name: "Boeing",             sector: "Industrials" },
  { symbol: "CAT",   name: "Caterpillar",        sector: "Industrials" },
  { symbol: "GE",    name: "GE Aerospace",       sector: "Industrials" },
  { symbol: "F",     name: "Ford",               sector: "Auto" },
  { symbol: "GM",    name: "General Motors",     sector: "Auto" },
  { symbol: "SPY",   name: "S&P 500 ETF",        sector: "ETF" },
  { symbol: "QQQ",   name: "Nasdaq 100 ETF",     sector: "ETF" },
  { symbol: "DIA",   name: "Dow 30 ETF",         sector: "ETF" },
  { symbol: "IWM",   name: "Russell 2000 ETF",   sector: "ETF" },
];